server:
  port: 8090

# Database connection properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yamis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
