server:
  port: 8090

# Database connection properties
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://106.52.14.176:3306/yamis
    username: yamis
    password: yamis123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# 网站设置
website:
  app_name: cocoyam
  logo: cocoyam
  footer: cocoyam
