server:
  port: 8090

# Database connection properties
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/yamis
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
